app/users/models.py
from app.database import BaseModel
from app.extensions import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))


class User(BaseModel, UserMixin):
	username = db.Column(db.String(30), unique=True, nullable=True)
	email = db.Column(db.String(60), unique=True, nullable=True)
	phone = db.Column(db.String(11), unique=True, nullable=False)

	def __repr__(self):
		return f'{self.__class__.__name__} ({self.id}, {self.username})'


class Code(BaseModel):
	number = db.Column(db.Integer)
	expire = db.Column(db.DateTime, nullable=False)
	phone = db.Column(db.String(11), unique=True, nullable=False)

	def __repr__(self):
		return f'{self.__class__.__name__} ({self.phone}, {self.number})'


class Follow(BaseModel):
	follower = db.Column(db.Integer)
	followed = db.Column(db.Integer)

app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import ValidationError
from app.users.models import User, Code


class UserRegistrationForm(FlaskForm):
	phone = StringField('Phone')

	def validate_phone(self, phone):
		codes = Code.query.filter_by(phone=phone.data)
		if codes:
			Code.query.filter_by(phone=phone.data).delete()

		user = User.query.filter_by(phone=phone.data).first()
		if user:
			raise ValidationError('This phone already exists')



class UserCodeVerifyForm(FlaskForm):
	code = StringField('Code')


class UserLoginForm(FlaskForm):
	phone = StringField('Phone')


class EmptyForm(FlaskForm):
	submit = SubmitField('submit')

app/__init__.py
from flask import Flask

from app.users.routes import blueprint as users_blueprint
from app.posts.routes import blueprint as posts_blueprint
import app.exceptions as app_exception
from app.extensions import db, migrate, login_manager
from app.users.models import User, Code, Follow


def register_blueprint(app):
	app.register_blueprint(users_blueprint)
	app.register_blueprint(posts_blueprint)

def register_error_handlers(app):
	app.register_error_handler(404, app_exception.page_not_found)
	app.register_error_handler(500, app_exception.server_error)


def register_shell_context(app):
	def shell_context():
		return {
			'db': db,
			'User': User,
			'Code': Code,
			'Follow': Follow,
		}
	app.shell_context_processor(shell_context)


app = Flask(__name__)
register_blueprint(app)
register_error_handlers(app)
register_shell_context(app)
app.config.from_object('config.DevConfig')

db.init_app(app)

from app.users.models import User # is here due to circular_imports for migrate use
migrate.init_app(app, db)
login_manager.init_app(app)


@app.before_request
def before_request():
	print('This is before any request')

@app.after_request
def after_request(response):
	print('This is after any request')
	print(response)
	return response   # middleware

app/posts/routes.py
from flask import Blueprint


blueprint = Blueprint('posts', __name__)


@blueprint.route('/posts')
def posts():
	return 'POSTS'

app/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from app.users.models import User, Code, Follow
from app.users.forms import UserRegistrationForm, UserCodeVerifyForm, UserLoginForm, EmptyForm
from app.extensions import db, sms_api
from flask_login import login_user, logout_user, current_user
import random
import datetime


blueprint = Blueprint('users', __name__)


@blueprint.route('/register', methods=['post', 'get'])
def register():
	form = UserRegistrationForm()
	if form.validate_on_submit():
		rand_num = random.randint(1000, 9999)
		session['user_phone'] = form.phone.data
		params = {'sender':'', 'receptor':int(form.phone.data), 'message':rand_num}
		sms_api.sms_send(params)
		code = Code(
					number=rand_num,
					expire=datetime.datetime.now() + datetime.timedelta(minutes=10),
					phone=form.phone.data
					)
		db.session.add(code)
		db.session.commit()
		return redirect(url_for('users.verify'))
	return render_template('users/register.html', form=form)


@blueprint.route('/verify', methods=['post', 'get'])
def verify():
	user_phone = session.get('user_phone')
	code = Code.query.filter_by(phone=user_phone).first()
	form = UserCodeVerifyForm()
	if form.validate_on_submit():
		if code.expire < datetime.datetime.now():
			flash('Expiration Error, please try again', 'danger')
			return redirect('users.register')

		if form.code.data != str(code.number):
			flash('your code is wrong', 'danger')
		else:
			user = User(phone=user_phone)
			db.session.add(user)
			db.session.commit()
			flash('your account created successfully', 'info')
			return redirect('/')
	return render_template('users/verify.html', form=form)


@blueprint.route('/login', methods=['post', 'get'])
def login():
	form = UserLoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(phone=form.phone.data).first()
		login_user(user)
		flash('you logged in')
		return redirect('/')
	return render_template('users/login.html', form=form)


@blueprint.route('/logout', methods=['get', 'post'])
def logout():
	logout_user()
	flash('you logged out')
	return redirect('/')


@blueprint.route('/profile')
def profile():
	return render_template('users/profile.html')


@blueprint.route('/user/<int:id>')
def user(id):
	following = False
	user = User.query.get_or_404(id)
	form = EmptyForm()
	relation = Follow.query.filter_by(follower=current_user.id, followed=user.id).first()
	if relation:
		following = True
	return render_template('users/user.html', user=user, form=form, following=following)


@blueprint.route('/follow/<int:user_id>', methods=['post'])
def follow(user_id):
	form = EmptyForm()
	if form.validate_on_submit():
		user = User.query.filter_by(id=user_id).first()
		if user is None:
			flash('User Not Found', 'danger')
			return redirect('/')
		if user == current_user:
			flash('you cant follow yourself', 'info')
			return redirect('/')
		relation = Follow(follower=current_user.id, followed=user.id)
		db.session.add(relation)
		db.session.commit()
		flash(f'you followed {user.phone}', 'info')
		return redirect(url_for('users.user', id=user.id))
	return redirect('/')


@blueprint.route('/unfollow/<int:user_id>', methods=['post'])
def unfollow(user_id):
	form = EmptyForm()
	if form.validate_on_submit():
		user = User.query.filter_by(id=user_id).first()
		if user is None:
			flash('User not found', 'danger')
			return redirect('/')
		if user == current_user:
			flash('you cant unfollow yourself', 'danger')
			return redirect('/')
		relation = Follow.query.filter_by(follower=current_user.id, followed=user.id).first()
		db.session.delete(relation)
		db.session.commit()
		flash(f'you unfollowed {user.phone}', 'info')
		return redirect(url_for('users.user', id=user.id))
	return redirect('/')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Blog</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>

    {% include 'includes/navbar.html' %}
    <div class="jumbotron">
        {% include 'includes/messages.html' %}
        {% block content %} {% endblock %}
    </div>

</body>
</html>

app/templates/includes/form_errors.html
{% if form.code and form.code.errors %}
  {% for error in form.code.errors %}
    <p class="alert alert-danger">{{ error }}</p>
  {% endfor %}
{% endif %}

{% if form.phone and form.phone.errors %}
  {% for error in form.phone.errors %}
    <p class="alert alert-danger">{{ error }}</p>
  {% endfor %}
{% endif %}

{% if form.verify and form.verify.errors %}
  {% for error in form.verify.errors %}
    <p class="alert alert-danger">{{ error }}</p>
  {% endfor %}
{% endif %}

app/templates/includes/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for cat, msg in messages %}
            <p class="alert alert-{{ cat }}">{{ msg }}</p>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Home</a>
    {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="{{ url_for('users.logout') }}">Logout</a>
        <a class="navbar-brand" href="{{ url_for('users.profile') }}">Profile</a>
    {% else %}
        <a class="navbar-brand" href="{{ url_for('users.register') }}">register</a>
        <a class="navbar-brand" href="{{ url_for('users.login') }}">Login</a>
    {% endif %}
</nav>

app/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    {% include 'includes/form_errors.html' %}
    <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.phone.label }} {{ form.phone }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h3>your logged in with {{ current_user.phone }}</h3>
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    {% include 'includes/form_errors.html' %}
    <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.phone.label }} {{ form.phone }}
        <input type="submit" value="register">
    </form>
{% endblock %}

app/templates/users/user.html
{% extends 'base.html' %}

{% block content %}
  {{ user.phone }}

  {% if current_user.is_authenticated and following %}
      <form action="{{ url_for('users.unfollow', user_id=user.id) }}" method="post">
        {{ form.csrf_token }}
        {{ form.submit(value='unfollow') }}
      </form>
  {% elif current_user.is_authenticated and not following %}
    <form action="{{ url_for('users.follow', user_id=user.id) }}" method="post">
      {{ form.csrf_token }}
      {{ form.submit(value='follow') }}
    </form>
  {% endif %}

{% endblock %}

app/templates/users/verify.html
{% extends 'base.html' %}

{% block content %}
    {% include 'includes/form_errors.html' %}
    <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.code.label }} {{ form.code }}
        <input type="submit" value="Verify">
    </form>
{% endblock %}